### PR TITLE
Feature/fs folders

### PR DESCRIPTION
**Pull request by BaldoHado**
Summary
- Changed GET users endpoint to check for username and password
- Added GET request to get all folders for a given user
- Connected Backend + Mongo to the frontend
- Separated Item Boxes for folders and items
- Added dynamic routes using the folder ids
- Added auth context to sustain a user id

Testing
- `npm start` in root
- `npm run dev` in backend
- Sign in with credentials
   - Username: bossbaby  | Password: a1234567890!AA
- Navigate to http://localhost:3000/inventory  
   - Verify that 2 folders populate
   - Click edit button and add a new folder
   - Verify that the new folder is visible on the page
   - Click that new folder and make sure it's empty
   - Go back. click edit button and delete the folder you just created
   - Click each folder and verify that items populate
   - You can go back with the back button on the top left
   - In a folder, add a new item, verify that it populates, then delete it
- Note: Images don't work yet

### CODE REVIEW

**Comment by AnsonWooo** [comment]
Looks good Adam! There are some minor things that should be changed:
- When creating a folder, it says item in the popup
- We also don't need a quantity when making a new folder

**Comment by Agwe422** [comment]
Looks great! I think it'd be good if we made images optional and have some stock images or blank colored images the user can pick from if they don't have one of their own

**Comment by BaldoHado** [comment]
> Looks good Adam! There are some minor things that should be changed:
> 
> * When creating a folder, it says item in the popup
> * We also don't need a quantity when making a new folder

These will be addressed in a future branch. The purpose of this PR is solely linking the FE to BE.

**Comment by BaldoHado** [comment]
> Looks great! I think it'd be good if we made images optional and have some stock images or blank colored images the user can pick from if they don't have one of their own

I agree. We can attempt to implement this in a future sprint.

**Comment by Luke7787** [comment]
Great work on this feature! The integration of the backend with MongoDB and the frontend, along with the dynamic routing and authentication context, looks solid.

**Comment by victorphan101** [comment]
The folder components look great and work well. A better addition for an intuitive design is to provide a set template or default folder for users to interact with when they create an account.

**Pull request merged**
